// <auto-generated />
namespace WorldCup2018.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateData));
        
        string IMigrationMetadata.Id
        {
            get { return "201802031918461_updateData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
